version: '3'
services:
    frontend:
        container_name: frontend
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        ports:
            - '4200:4200'
